CREATE TABLE customer (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  CUSTOMER_NAME varchar(50) DEFAULT NULL,
  DATE_DOB datetime DEFAULT NULL,
  EMAIL varchar(50) DEFAULT NULL,
  CREATED_BY varchar(50) DEFAULT NULL,
  CREATED_DATE datetime DEFAULT NULL,
  IS_VALID bit(1) DEFAULT NULL,
  MODIFIED_BY varchar(50) DEFAULT NULL,
  MODIFIED_DATE datetime DEFAULT NULL,
  STATUS varchar(255) DEFAULT NULL,
  CUSTOMER_TYPE varchar(12) DEFAULT NULL,
  ADDRESS_ID INTEGER DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE customer_address (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  CITY_DISTRICT varchar(50) DEFAULT NULL,
  COUNTRY varchar(50) DEFAULT NULL,
  CUSTOMER_NAME varchar(50) DEFAULT NULL,
  MOBILE varchar(15) DEFAULT NULL,
  PHONE varchar(15) DEFAULT NULL,
  STATE varchar(50) DEFAULT NULL,
  STREET_ADDRESS varchar(200) DEFAULT NULL,
  ZIPCODE int(11) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE customer_order (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  AMOUNT_FINAL_BILLING double DEFAULT NULL,
  AMOUNT_ITEMS_SUM double DEFAULT NULL,
  AMOUNT_PAID double DEFAULT NULL,
  OTHER_DETAILS varchar(100) DEFAULT NULL,
  ORDER_STATUS varchar(100) DEFAULT NULL,
  CREATED_BY varchar(50) DEFAULT NULL,
  CREATED_DATE datetime DEFAULT NULL,
  IS_VALID bit(1) DEFAULT NULL,
  MODIFIED_BY varchar(50) DEFAULT NULL,
  MODIFIED_DATE datetime DEFAULT NULL,
  CUSTOMER_ID INTEGER DEFAULT NULL,
  DELIVERY_ADDRESS_ID INTEGER DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE customer_order_item (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  COMMENTS varchar(100) DEFAULT NULL,
  ORDER_ITEM_STATUS varchar(20) NOT NULL,
  QUANTITY INTEGER DEFAULT NULL,
  CREATED_BY varchar(50) DEFAULT NULL,
  CREATED_DATE datetime DEFAULT NULL,
  IS_VALID bit(1) DEFAULT NULL,
  MODIFIED_BY varchar(50) DEFAULT NULL,
  MODIFIED_DATE datetime DEFAULT NULL,
  SELLING_PRICE double DEFAULT NULL,
  ORDER_ID INTEGER DEFAULT NULL,
  PRODUCT_ID INTEGER DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE customer_order_payments (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  AMOUNT double DEFAULT NULL,
  CARD_NUMBER varchar(50) DEFAULT NULL,
  OTHER_DETAILS varchar(50) DEFAULT NULL,
  PAYMENT_METHOD varchar(10) NOT NULL,
  CREATED_BY varchar(50) DEFAULT NULL,
  CREATED_DATE datetime DEFAULT NULL,
  IS_VALID bit(1) DEFAULT NULL,
  MODIFIED_BY varchar(50) DEFAULT NULL,
  MODIFIED_DATE datetime DEFAULT NULL,
  ORDER_ID INTEGER DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE employee (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  empName varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE product (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  DESCRIPTION varchar(255) DEFAULT NULL,
  NAME varchar(50) NOT NULL,
  CREATED_BY varchar(50) DEFAULT NULL,
  CREATED_DATE datetime DEFAULT NULL,
  IS_VALID bit(1) DEFAULT NULL,
  MODIFIED_BY varchar(50) DEFAULT NULL,
  MODIFIED_DATE datetime DEFAULT NULL,
  CATEGORY_ID INTEGER NOT NULL,
  SUPPLIER_ID INTEGER DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE product_category (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  DESCRIPTION varchar(500) DEFAULT NULL,
  NAME varchar(50) NOT NULL,
  CREATED_BY varchar(50) DEFAULT NULL,
  CREATED_DATE datetime DEFAULT NULL,
  IS_VALID bit(1) DEFAULT NULL,
  MODIFIED_BY varchar(50) DEFAULT NULL,
  MODIFIED_DATE datetime DEFAULT NULL,
  PARENT_CATEGORY_ID INTEGER DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE product_item (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  COLOUR varchar(255) DEFAULT NULL,
  MRP_AMOUNT double DEFAULT NULL,
  SIZE varchar(255) DEFAULT NULL,
  CREATED_BY varchar(50) DEFAULT NULL,
  CREATED_DATE datetime DEFAULT NULL,
  IS_VALID bit(1) DEFAULT NULL,
  MODIFIED_BY varchar(50) DEFAULT NULL,
  MODIFIED_DATE datetime DEFAULT NULL,
  PRODUCT_ID INTEGER NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE supplier (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  DESCRIPTION varchar(500) DEFAULT NULL,
  NAME varchar(50) DEFAULT NULL,
  CREATED_BY varchar(50) DEFAULT NULL,
  CREATED_DATE datetime DEFAULT NULL,
  IS_VALID bit(1) DEFAULT NULL,
  MODIFIED_BY varchar(50) DEFAULT NULL,
  MODIFIED_DATE datetime DEFAULT NULL,
  PRIMARY KEY (ID)
);
